### ISSUE TITLE
Error with horizontal mouse cropping

### ISSUE THREAD

**Issue by akenet** [soorajachar/radianceQuantifier#4]
In this example, only part of the mouse's tail is shown when plotting all the images. The entire mouse is visible in the brightfield.TIF image and the luminescent.PNG image.

Image when plotted:
<img width="118" alt="mouse_cropping_error_example" src="https://github.com/soorajachar/radianceQuantifier/assets/70348097/d6d9babd-fbfb-4d10-a75f-825994a2b887">

Screenshot of brightfield.TIF
<img width="506" alt="brightfield TIF screenshot" src="https://github.com/soorajachar/radianceQuantifier/assets/70348097/b39a8995-6cd7-4afe-9784-185ff7b36896">

**Comment by soorajachar** [comment]
Should be fixed in version 0.4.16
